SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS stores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  address VARCHAR(240) NOT NULL,
  manager_id INT NULL,
  status ENUM('OPEN','RENOVATING','CLOSED') NOT NULL DEFAULT 'OPEN',
  phone VARCHAR(30) NOT NULL,
  business_hours VARCHAR(80) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_no VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(60) NOT NULL,
  department VARCHAR(60) NOT NULL,
  position VARCHAR(60) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(120) NOT NULL,
  join_date DATE NOT NULL,
  status ENUM('ON_PROBATION','ACTIVE','RESIGNED') NOT NULL,
  salary DECIMAL(12,2) NOT NULL,
  role ENUM('OWNER','MANAGER','EMPLOYEE') NOT NULL,
  store_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_employee_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL
);

ALTER TABLE stores
  ADD CONSTRAINT fk_store_manager FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(120) NOT NULL,
  role ENUM('OWNER','MANAGER','EMPLOYEE') NOT NULL,
  employee_id INT NULL,
  store_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL,
  CONSTRAINT fk_user_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS permissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role ENUM('OWNER','MANAGER','EMPLOYEE') NOT NULL,
  module VARCHAR(60) NOT NULL,
  action VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS shifts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_id INT NOT NULL,
  date DATE NOT NULL,
  shift_type ENUM('MORNING','AFTERNOON','NIGHT','REST') NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  store_id INT NOT NULL,
  status ENUM('PENDING','CONFIRMED','CHECKED_IN') NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_shift_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  CONSTRAINT fk_shift_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type ENUM('INCOME','EXPENSE') NOT NULL,
  category ENUM('SALARY','PURCHASE','RENT','UTILITY','SALES','OTHER') NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  description TEXT NOT NULL,
  related_employee_id INT NULL,
  store_id INT NOT NULL,
  date DATE NOT NULL,
  receipt VARCHAR(255) NULL,
  reviewed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_transaction_employee FOREIGN KEY (related_employee_id) REFERENCES employees(id) ON DELETE SET NULL,
  CONSTRAINT fk_transaction_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  operator_id INT NULL,
  action VARCHAR(80) NOT NULL,
  target VARCHAR(120) NOT NULL,
  old_value TEXT NULL,
  new_value TEXT NULL,
  ip VARCHAR(60) NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_operator FOREIGN KEY (operator_id) REFERENCES users(id) ON DELETE SET NULL
);
